import type { TReport, TSourcedString } from "@/lib/schemas/passport";

const sv = (s: TSourcedString): string => s.value ?? "Not verified";

export function buildMarkdown(report: TReport): string {
  const p = report.passport;
  const lines: string[] = [];
  lines.push(`# RWA Passport — ${p.identity.name}${p.identity.ticker ? ` (${p.identity.ticker})` : ""}`);
  if (report.demo) lines.push(`\n> Demo report — curated illustrative research, not live analysis.`);
  lines.push(`\n${p.identity.oneLiner}`);
  lines.push(`\n**RWA Score: ${report.scores.overall}/100 — ${report.scores.label}**`);
  lines.push(
    `\n_Research score based on transparency, asset structure, liquidity, redemption, custody and available risk signals. Not investment advice._`
  );
  lines.push(`\n## Category Scores\n`);
  for (const c of report.scores.categories) lines.push(`- ${c.label}: ${c.score}${c.note ? ` — ${c.note}` : ""}`);
  lines.push(`\n## Summary\n\n${p.summary}`);
  lines.push(`\n## What You're Actually Buying\n\n${p.whatYouAreBuying}`);
  lines.push(`\n## Asset\n`);
  lines.push(`- Underlying asset: ${sv(p.asset.underlyingAsset)}`);
  lines.push(`- Asset class: ${sv(p.asset.assetClass)}`);
  lines.push(`- Issuer: ${sv(p.asset.issuer)}`);
  lines.push(`- Product structure: ${sv(p.asset.productStructure)}`);
  lines.push(`- Currency: ${sv(p.asset.currency)}`);
  lines.push(`- Reported AUM: ${sv(p.asset.reportedAum)}`);
  lines.push(`- Yield mechanism: ${sv(p.asset.yieldMechanism)}`);
  lines.push(`\n## Token\n`);
  lines.push(`- Symbol: ${sv(p.token.symbol)}`);
  lines.push(`- Blockchain: ${sv(p.token.blockchain)}`);
  lines.push(`- Contract: ${sv(p.token.contract)}`);
  lines.push(`- Standard: ${sv(p.token.standard)}`);
  lines.push(`- Transferability: ${sv(p.token.transferability)}`);
  lines.push(`- Mint/burn: ${sv(p.token.mintBurn)}`);
  lines.push(`- Supply: ${sv(p.token.supply)}`);
  lines.push(`\n## Yield\n`);
  lines.push(`- Source: ${sv(p.yield.source)}`);
  lines.push(`- Reported APY: ${sv(p.yield.reportedApy)}`);
  lines.push(`- Distribution: ${sv(p.yield.distribution)}`);
  if (p.yield.sustainability) lines.push(`- Sustainability: ${p.yield.sustainability}`);
  lines.push(`\n## Redemption\n`);
  lines.push(`- Available: ${sv(p.redemption.available)}`);
  lines.push(`- Minimum: ${sv(p.redemption.minimum)}`);
  lines.push(`- Settlement: ${sv(p.redemption.settlementTime)}`);
  lines.push(`- Currency: ${sv(p.redemption.currency)}`);
  lines.push(`- Restrictions: ${sv(p.redemption.restrictions)}`);
  if (p.redemption.primaryVsSecondary) lines.push(`- Primary vs secondary: ${p.redemption.primaryVsSecondary}`);
  lines.push(`\n## Custody\n`);
  lines.push(`- Asset custodian: ${sv(p.custody.assetCustodian)}`);
  lines.push(`- Token custody dependencies: ${sv(p.custody.tokenCustodyDependencies)}`);
  lines.push(`- Service providers: ${sv(p.custody.serviceProviders)}`);
  lines.push(`- Offchain dependencies: ${sv(p.custody.offchainDependencies)}`);
  lines.push(`\n## Legal Structure\n`);
  lines.push(`- Jurisdiction: ${sv(p.legal.jurisdiction)}`);
  lines.push(`- Structure: ${sv(p.legal.structure)}`);
  lines.push(`- Eligibility: ${sv(p.legal.eligibility)}`);
  lines.push(`- KYC: ${sv(p.legal.kyc)}`);
  lines.push(`- Transfer restrictions: ${sv(p.legal.transferRestrictions)}`);
  lines.push(`- Regulatory notes: ${sv(p.legal.regulatoryNotes)}`);
  lines.push(`\n## Liquidity\n`);
  lines.push(`- Markets: ${sv(p.liquidity.markets)}`);
  lines.push(`- DEX/CEX availability: ${sv(p.liquidity.dexCexAvailability)}`);
  lines.push(`- Reported liquidity: ${sv(p.liquidity.reportedLiquidity)}`);
  lines.push(`- Primary redemption: ${sv(p.liquidity.primaryRedemption)}`);
  lines.push(`- Concentration: ${sv(p.liquidity.concentration)}`);
  if (p.liquidity.limitations) lines.push(`- Limitations: ${p.liquidity.limitations}`);
  lines.push(`\n## Multichain\n`);
  for (const c of p.multichain.chains) lines.push(`- ${c.chain} (${c.interoperability})`);
  if (p.multichain.notes) lines.push(`\n${p.multichain.notes}`);
  lines.push(`\n## Risks\n`);
  for (const r of p.risks) lines.push(`- **${r.category}** — ${r.level}: ${r.explanation}`);
  if (p.redFlags.length) {
    lines.push(`\n## What Deserves a Closer Look\n`);
    for (const rf of p.redFlags) lines.push(`- ${rf}`);
  }
  lines.push(`\n## Questions To Ask\n`);
  for (const q of p.questionsToAsk) lines.push(`- ${q}`);
  if (p.sources.length) {
    lines.push(`\n## Sources\n`);
    for (const s of p.sources) lines.push(`- ${s.title ? `${s.title}: ` : ""}${s.url}`);
  }
  lines.push(`\n---\n\nGenerated by TokenRWA (tokenrwa.net). Research tool — not investment advice.`);
  return lines.join("\n");
}

/** Compact research context for the chat assistant. */
export function buildChatContext(report: TReport): string {
  return buildMarkdown(report).slice(0, 50_000);
}
